[phases.setup]
nixPkgs = ["nodejs_20"]

[phases.install]
cmds = ["cd client && npm ci --legacy-peer-deps"]

[phases.build]
cmds = ["cd client && npm run build"]

[start]
cmd = "node client/server.js"
